add_rules("mode.debug", "mode.release")
add_repositories("my-repo git@github.com:Moon-Ocean/xmake-repo.git")
 
add_requires("gtest")
add_requires("libapng")
add_requires("libwebp 1.2.0")
add_requires("libomp", {optional = true})
set_targetdir("build")
set_symbols("debug")
includes("DgaImage")

target("KoiAnimation")
    add_rules("c++.openmp")
    add_rules("qt.shared")
    add_deps("DgaImage")
    add_includedirs("DgaImage")
    add_frameworks("core", "QtGui")
    add_packages("libomp")
    add_packages("libapng", "libwebp")
    add_defines("KOIANIMATION_LIB")
    add_includedirs("include")
    add_headerfiles("include/KoiAnimation.h", "include/koianimation_global.h")
    add_headerfiles("include/KoiMovie.h")
    add_headerfiles("include/KoiConvert.h")
    add_headerfiles("include/AniImageProcess.h")
    add_files("include/KoiMovie.h")
    add_files("src/*.cpp") 
    add_files("include/KoiAnimation.h") 
    add_files("include/KoiConvert.h")

target("test")
    add_rules("qt.console") 
    add_packages("gtest")
    add_deps("DgaImage")
    add_frameworks("core", "QtGui")
    add_deps("KoiAnimation")
    add_includedirs("include")
    add_files("test/*.cpp") 
    add_files("test/*.qrc")  
    add_deps("DgaImage")
    add_includedirs("DgaImage")